import { SceneData, ChoiceOption, CombinedConsequence, StoryEnding, TonightSituationState } from './contracts';

export interface Fiction { minutes: number; neighbor: number; delivery: string; laptop: string; dessert: string; work: string; kit: boolean; rooftop: boolean; keepsake: string; }
export const initialFiction = (): Fiction => ({ minutes: 25, neighbor: 0, delivery: 'At the locked entrance', laptop: 'Dry and open', dessert: 'Unopened box', work: 'Webinar invitation unread', kit: false, rooftop: false, keepsake: 'No souvenir yet' });
type Effect = Partial<Fiction> & { time?: number; goodwill?: number };
interface Beat { title: string; text: string; effect: Effect; }
interface ChapterScene { title: string; setting: string; event: string; host: string; guest: string; goal: string; stakes: string; prompt: string; h: [string,string][]; g: [string,string][]; results: [Beat,Beat,Beat,Beat]; }
const b = (title: string, text: string, effect: Effect = {}): Beat => ({title,text,effect});

// Each scene has four individually authored pair outcomes: H0/G0, H0/G1, H1/G0, H1/G1.
export const script: ChapterScene[] = [
  {
    title: 'The Buzzer Has a Solo', setting: 'Two apartments, one very loud entrance',
    event: 'The date begins with two candles, two carefully angled webcams, and a toast interrupted by a noise like a duck trapped in a printer. The host\'s apartment buzzer has jammed. Downstairs, courier Rosa holds a paper bag away from the rain. Her message reads: "I pressed once. The building is doing the rest." Through the wall comes one deliberate knock, followed by Mr. Henderson saying, "Some of us are listening to a documentary about silence." The guest can call Rosa through the shared delivery link or phone the building desk; the host can reach the intercom or go downstairs.',
    host: 'I rehearsed saying you look nice. I did not rehearse being introduced by industrial waterfowl. If I hold this button, can you tell me whether anyone can actually hear me?',
    guest: 'You look nice. Your building sounds single. Rosa has two minutes before her next pickup, so let us give her exactly one useful instruction before she starts dating someone with a working door.',
    goal: 'Get Rosa through the locked entrance before she leaves.', stakes: 'Conflicting instructions cost preparation time; the buzzer is upsetting the neighbor.', prompt: 'Who handles the door, and who gives directions?',
    h: [['Use the intercom','Hold the talk switch and ask Rosa to push the door.'],['Meet Rosa downstairs','Carry your phone down three flights and open the door yourself.']],
    g: [['Call Rosa','Use the shared delivery link to tell Rosa where to wait.'],['Call the building desk','Ask the caretaker to release the entrance remotely.']],
    results: [b('Two Voices, No Door','The host shouts "push" through the intercom while the guest tells Rosa to wait on the phone. Rosa carefully does neither. The buzzer finally stops when the host lets go. "Excellent rehearsal," she says. "Shall we try a door next?" She waits, but the extra calls eat into the dinner buffer.',{time:-4,delivery:'Rosa waiting at entrance',goodwill:-1}),b('An Accidental Door Team','The host holds the talk switch while the guest reaches the caretaker. A remote click lands halfway through "please push," and Rosa glides inside as though you planned sound effects. Henderson opens his door just far enough to say, "A short composition. Thank you."',{time:2,delivery:'Rosa coming upstairs',goodwill:1}),b('The Human Doorbell','The host appears downstairs, slightly breathless, just as the guest tells Rosa to look for the person waving a phone. Rosa waves her bag back. "Finally, a recognizable landmark." The host walks her upstairs and the guest gets a surprisingly cinematic tour of the stairwell ceiling.',{delivery:'Handed over in stairwell',time:-1}),b('An Entrance with an Encore','The host opens the entrance by hand at the exact moment the guest persuades the caretaker to release it. The unnecessary mechanism gives one last squawk. Henderson calls "Encore declined!" Rosa laughs, but the host climbs three flights carrying dinner and a very public introduction.',{delivery:'Handed over in stairwell',time:-2,goodwill:-1})]
  },
  {
    title: 'The Napkin Treaty', setting: 'Outside apartment 3B',
    event: 'Rosa reaches the landing, or the host returns there to collect her. Henderson is now standing outside 3B in slippers embroidered with small anchors. He has brought a notebook headed NOISE, which seems excessive for a one-word subject. A napkin flutters out of the takeout bag and lands on his slipper. The guest is still visible on the host\'s phone. Henderson peers at the screen. "Is this the committee?" There is time for a proper apology or a quick explanation, but dinner is cooling and he will remember how this conversation ends.',
    host: 'That napkin was not a formal declaration. I am sorry about the buzzer. We are attempting dinner, which has so far involved very little sitting down.',
    guest: 'I can offer a sincere apology from another postal district, or I can explain the broken switch. I suspect the notebook has room for either, but perhaps not for a joke about maritime law.',
    goal: 'Settle the noise complaint without promising something impossible.', stakes: 'Henderson may later lend supplies or insist you manage alone.', prompt: 'Make peace personally, or keep the interruption short?',
    h: [['Give a proper apology','Pick up the napkin and acknowledge the interruption.'],['Explain the faulty buzzer','Point to the building problem and hurry dinner inside.']],
    g: [['Back the apology','Thank Henderson for his patience without making excuses.'],['Offer a quiet-hours plan','Promise the call will move away from his wall.']],
    results: [b('A Complaint Withdrawn','The host retrieves the napkin and apologizes; the guest adds a quiet thank-you. Henderson closes NOISE without writing. "I also once tried to impress someone with takeaway," he admits. "Do not use the little plastic forks. They betray you." He offers to help if the evening needs proper equipment.',{goodwill:2,time:-1}),b('The Wall Agreement','The host apologizes while the guest suggests moving the call to the kitchen. Henderson draws a tiny apartment plan on the rescued napkin. "This wall conducts bass. This one merely conducts gossip." You now have both a quieter location and a neighbor willing to advise.',{goodwill:2}),b('A Conditional Truce','The host blames the switch, but the guest thanks Henderson for enduring it. He looks from the hurried hand on the doorknob to the earnest face on the phone. "One of you has excellent manners by satellite." He accepts the apology, though he keeps his notebook.',{goodwill:1,time:-1}),b('Quiet, on Paper','The host explains the wiring and the guest promises to move the call. Henderson writes "kitchen" in NOISE. "Then I shall expect the kitchen." Dinner gets indoors quickly, but he hears a plan for avoiding him rather than an apology. He will not volunteer assistance.',{goodwill:-1,time:1})]
  },
  {
    title: 'A Bag with Two Names', setting: 'Kitchen counter and the courier chat',
    event: 'The bag contains your noodles, an alarming quantity of dipping sauce, and a sealed dessert box marked BERNARD. Rosa checks her delivery app at the landing. Bernard lives in the next building and has apparently received your receipt. The restaurant phones Rosa: both boxes contain the same cannoli, but Bernard requested no pistachios. There is a printed ingredient label on the bottom. Nobody needs to taste anything to solve this. Rosa can swap the labeled boxes before leaving, or record the mix-up for a refund. Barnaby, Henderson\'s small dog, watches the paperwork with the grave interest of an auditor.',
    host: 'I invited you to dinner and have accidentally become Bernard. It is a strong name for someone who owns this many sauce pots, but I should probably check the label.',
    guest: 'I have the order receipt. We can help Rosa fix the labels, or keep our own food and refund the uncertain dessert. The dog is offering a third option which we will not be taking.',
    goal: 'Identify your food and resolve the mislabeled dessert.', stakes: 'Rushing may leave you with crushed dessert; a careful check costs a little time.', prompt: 'Check the box together or prioritize the hot food?',
    h: [['Read the underside label','Support the box flat and read Rosa the ingredient label.'],['Unpack the noodles now','Set the dessert aside while getting dinner onto plates.']],
    g: [['Read the receipt to Rosa','Compare the order number and topping with the courier.'],['Request a dessert refund','Tell Rosa to collect the uncertain box and log the mistake.']],
    results: [b('Bernard Gets His Name Back','The host reads the label while the guest reads the receipt. Rosa swaps the two boxes without opening either. "I have delivered identity itself," she announces. Barnaby sneezes at the paperwork. Your correct cannoli sit safely on the counter and Rosa sends a grateful thumbs-up.',{delivery:'Correct dinner delivered',dessert:'Intact cannoli',time:-1}),b('A Refund with Hot Noodles','The host confirms the label, and the guest requests collection rather than a swap. Rosa removes Bernard\'s box and records the refund. "A decisive committee." The noodles are yours, the dessert is gone, and the guest writes TOAST? on a scrap of paper for later.',{delivery:'Correct dinner delivered',dessert:'Refunded; replacement needed',time:1}),b('The Receipt Is Not a Tray','The host lifts the noodles while the guest reads the receipt aloud. The unsupported dessert box tilts into the bag. Rosa corrects the order, but a cream smear appears in its window. "Same ingredients," she says. "New architecture." Dinner is right; dessert will require presentation skills.',{delivery:'Correct dinner delivered',dessert:'Crushed cannoli',time:-1}),b('A Clean Exit for Rosa','The host plates the hot noodles while the guest requests a refund. Rosa takes the sealed dessert away. You finally sit down before dinner turns cold. Through the phone, the guest raises their own plate: "To Bernard, wherever he may dine." Dessert is now a future problem.',{delivery:'Correct dinner delivered',dessert:'Refunded; replacement needed',time:2})]
  },
  {
    title: 'Table for One Phone', setting: 'A kitchen with ambitious lighting',
    event: 'Dinner has reached the kitchen, but the phone cannot see both the host and the plate. Its improvised stand is a paperback romance called A Sensible Arrangement, balanced on the open work laptop. A sauce pot leans against the hinge. The guest\'s setup is hardly more dignified: their camera sits inside a mug, so every nod looks like an earthquake. There is an empty baking tray on the host\'s stove and a folded tea towel by the sink. The guest can suggest a practical layout or spend the moment getting the lighting just right. The candles are electric; at least one disaster has been designed out.',
    host: 'The book promised a sensible arrangement. I feel entitled to a refund. If I move the laptop now, you will briefly see the underside of my chin, which has not dressed for dinner.',
    guest: 'My camera is being held up by a mug that says TEAM PLAYER. It has contributed more than most teams. Give me ten seconds and we can either secure the dinner or make it look like a film poster.',
    goal: 'Make a stable place for dinner and the video call.', stakes: 'A protected workspace is safer when the sauce pots come open.', prompt: 'Spend the pause on spill protection or the perfect picture?',
    h: [['Use the baking tray','Put the sauce pots in a rimmed tray and fold the towel nearby.'],['Adjust the phone angle','Leave dinner by the laptop and improve the camera framing.']],
    g: [['Talk through a tidy layout','Ask for space around the laptop and a towel within reach.'],['Direct the candle lighting','Help frame the two plates and the warm lights.']],
    results: [b('A Very Sensible Arrangement','The host corrals the pots in the tray while the guest talks the laptop onto a dry shelf. The towel becomes a modest spill kit. The camera now includes a corner of the fridge, but also two people visibly relaxing. "Five stars," says the guest. "Excellent drainage."',{kit:true,time:1}),b('Practical, with Mood Lighting','The host builds a sauce corral while the guest directs the candles into a glowing line. The resulting tray looks like a tiny luxury swimming pool. The towel remains within reach. "No diving," says the host to the sauce. This joke is unfortunately going to become relevant.',{kit:true}),b('The Guest Spots the Hinge','The host fixes the framing; the guest interrupts the glamour shoot to point out the sauce beside the laptop hinge. A towel gets folded underneath the pots before the next photograph. The laptop stays open, but the spill kit is ready and the picture includes a heroic amount of fabric.',{kit:true,time:-1}),b('A Beautifully Framed Hazard','The host raises the phone while the guest directs warm light across the plate. It looks gorgeous. The sauce remains beside the open laptop, just outside the photograph. "Nobody needs to see the infrastructure," says the host. The infrastructure waits patiently to become the plot.',{kit:false,time:2})]
  },
  {
    title: 'The First Actual Bite', setting: 'Dinner, almost uninterrupted',
    event: 'For the first time tonight, both forks reach food at the same time. Then the host\'s work laptop lights up: "Optional international showcase begins shortly. Presenter requested: YOU." A calendar update has promoted a tentative invitation into a live demonstration. The host only owes the team a thirty-second introduction to a document already shared. A chat window offers a chance to warn the moderator now; ignoring it might buy an uninterrupted minute but leave a public surprise. The guest has their own dinner and cannot control the host\'s machine, though they can help draft a reply or keep the date conversation going.',
    host: 'Optional is doing a lot of unpaid labor in that sentence. I promised them a document, not a live cooking segment. I can send a boundary now, or hope someone notices my absence before they notice my face.',
    guest: 'Tell them dinner is an appointment. You are allowed an appointment that includes noodles. Also, for the record, I was enjoying the bit where neither of us was speaking to a building.',
    goal: 'Decide how much notice the work moderator gets.', stakes: 'Early notice buys a calmer exit from the webinar; silence leaves your slot live.', prompt: 'Set a work boundary now, or protect this first quiet minute?',
    h: [['Send a short boundary','Tell the moderator you can provide text but cannot present tonight.'],['Close the notification','Take the first bite and deal with the invitation if it returns.']],
    g: [['Draft a friendly sentence','Suggest a clear message with the shared document link.'],['Offer a dinner toast','Raise your glass and reclaim a minute of the date.']],
    results: [b('A Link Instead of a Performance','The host sends the guest\'s concise wording and the document link. The moderator replies with a thumbs-up and moves the slot to text. "To an email doing its job," says the host. Both finally take a bite. The webinar may still open, but the team knows not to expect a performance.',{work:'Text-only slot agreed',time:2}),b('A Boundary and a Toast','The host types a brief refusal while the guest raises a glass. The moderator acknowledges the message, though the host forgets the document link. Your first toast is "To attachments, eventually." There is still a tiny work task to finish, but the live introduction is cancelled.',{work:'Text-only slot agreed',time:1}),b('An Unsent Masterpiece','The guest drafts a graceful sentence; the host closes the notification before sending it. The proposed wording hangs in the date chat like an excellent umbrella left indoors. Dinner gets one quiet minute. The moderator still has the host listed as a live presenter.',{work:'Live slot still scheduled',time:1}),b('To Strategic Denial','The host closes the notification and the guest offers a toast to dinner finally happening. For a whole minute it works. You compare noodles and laugh about Bernard. Behind the phone stand, the calendar badge counts down toward a live slot nobody has cancelled.',{work:'Live slot still scheduled',time:2})]
  },
  {
    title: 'Sauce at the Hinge', setting: 'The kitchen becomes a rescue desk',
    event: 'The first sauce pot opens with an unexpectedly athletic pop. A bead of chili glaze lands at the lip of the work laptop while the webinar reminder opens across its screen. The host has one hand on the lid and one holding dinner. The guest can see the red bead growing through the video call. Nobody should keep using a wet computer to save a meeting. There is time to close and unplug the laptop before liquid gets under the keys, or to move the entire tray and hope the spill protection holds. The guest can call out the dry shelf or help locate a towel.',
    host: 'That sauce has career ambitions. It is heading directly for the keyboard. Please give me one instruction at a time; I am currently holding both dinner and a lid with something to prove.',
    guest: 'The meeting can survive without you. The laptop might prefer electricity to be a separate course. I can see the dry shelf behind your shoulder and the towel by the sink. Choose a destination; I will navigate.',
    goal: 'Separate sauce, electricity, and the open work laptop.', stakes: 'A spill can force the rest of the night onto a phone; the earlier towel setup matters.', prompt: 'Protect the laptop first or shift the whole dinner tray?',
    h: [['Close and unplug','Stop using the laptop, unplug it, and lift it to the dry shelf.'],['Shift the dinner tray','Move food away in one motion; rely on any towel already prepared.']],
    g: [['Guide toward the dry shelf','Keep instructions short and identify the clear landing space.'],['Call out the towel','Point out where to catch the spreading sauce before it runs.']],
    results: [b('An Unscheduled Shutdown','The host closes and unplugs the laptop while the guest talks it onto the dry shelf. The sauce reaches the old footprint one second later. "Your computer has left the meeting," says the guest. "Your dinner remains available." The dry machine can be reopened after the counter is clean.',{laptop:'Dry; safely moved',time:-1}),b('The Towel Has a Promotion','The host lifts the unplugged laptop while the guest points out the towel. The host drops the towel onto the bead with an undignified elbow maneuver. Nothing enters the keys. The sauce is contained, and the towel has become the evening\'s most qualified employee.',{laptop:'Dry; safely moved',kit:true}),b('The Long Way Round','The host pulls the dinner away while the guest calls out the shelf. The laptop stays in the spill zone during the turn. If a towel was laid earlier, it catches the glaze; otherwise a red line slips beneath the keys and the host immediately powers down. The meeting will have to wait for the damage assessment.',{time:-3}),b('The Great Tray Migration','The host shifts the tray as the guest directs a towel toward its trailing edge. Prepared fabric catches the spill cleanly; without it, the trip to the sink is one second too long. The host shuts the laptop off if wet. "Nobody is putting this in rice," the guest says firmly.',{time:-2})]
  },
  {
    title: 'You Are Now a Panelist', setting: 'A webinar that did not order dinner',
    event: 'The host\'s phone receives the webinar link just as the counter becomes safe. It is separate from your date call, which can remain audio-only for a moment. The moderator has found the shared document but wants confirmation of its title. There is a text chat button and a microphone button uncomfortably close together. The guest can feed the exact title through your private date chat or hold up a handwritten cue card to the webcam. If the laptop is wet it stays powered off; joining from the phone is the only option. The company audience is not a villain, merely thirty people who would also like to go home.',
    host: 'The title is "Reducing Friction." I have just used a towel to do that literally. I can answer in text, or give them thirty seconds of voice and hope no one requests a demonstration.',
    guest: 'I can type the title or make a cue card. I will not impersonate an employee. My qualifications are one warm meal and a demonstrated ability to point at shelves.',
    goal: 'Give the moderator the title without turning dinner into a presentation.', stakes: 'A voice appearance can become a longer obligation if no boundary was sent.', prompt: 'Use the webinar text chat or make a brief voice appearance?',
    h: [['Reply in text','Send the document title and keep the microphone off.'],['Give a voice introduction','Read a brief introduction through the phone microphone.']],
    g: [['Send a private title cue','Type the exact title into the date chat for easy copying.'],['Hold up a cue card','Write the title large and show it to the host on camera.']],
    results: [b('Friction Reduced','The guest types the title; the host copies it into webinar chat with the link. The moderator answers "Received, enjoy your evening." Nobody sees the sauce. You return to the date call feeling as though you have successfully smuggled leisure through customs.',{work:'Finished by text',time:2}),b('A Card Nobody Else Sees','The guest holds REDUCING FRICTION to the camera. The host carefully transcribes it into webinar chat, keeping the microphone off. The moderator thanks them. The card tilts to reveal the guest has added "WITH NAPKINS" underneath. Only one audience member gets that edition.',{work:'Finished by text',keepsake:'Reducing Friction cue card'}),b('A Competent Thirty Seconds','The guest sends the exact title and the host reads a clean voice introduction. The moderator starts to ask a question, then checks the earlier messages. Whether you had already set a boundary determines how easy this exit feels; the host repeats that the document contains the details and signs off.',{work:'Voice introduction completed',time:-2}),b('The Unofficial Slide Deck','The guest holds up the cue card while the host speaks. The host reads the small "WITH NAPKINS" line too, pauses, and says, "That subtitle is internal." A few microphone icons flicker with laughter. The moderator accepts the link, but the extra explanation eats into dinner.',{work:'Voice introduction completed',time:-3,keepsake:'Reducing Friction cue card'})]
  },
  {
    title: 'A Knock with Equipment', setting: 'The kitchen door',
    event: 'Henderson knocks twice. "I heard a sentence about napkins," he says through the door. "Was it a request?" He has a clean dish towel and a small thermos. Barnaby waits behind his ankles, wearing a bow tie that suggests better plans. How Henderson was treated on the landing shapes whether this is a friendly supply visit or a reminder to keep voices down. The host can ask for practical help or reassure him and manage with household supplies. The guest can thank him directly through the phone or keep the call muted while the host handles the conversation.',
    host: 'There was a minor sauce event. Everyone is safe. Some equipment is having a quiet evening. I cannot promise the phrase "reducing friction" will ever sound normal again.',
    guest: 'I am available as a character witness, although my testimony consists mostly of "I told them about the shelf." You decide whether this is a neighbor conversation or a tiny press conference.',
    goal: 'Handle the interruption and obtain any cleanup help on offer.', stakes: 'Prior courtesy determines whether Henderson lends his supplies.', prompt: 'Invite practical help or finish the cleanup yourselves?',
    h: [['Ask for the clean towel','Explain the spill and ask to borrow the spare.'],['Keep the cleanup private','Thank him at the door and fetch your own spare cloth.']],
    g: [['Thank Henderson aloud','Address him by name and acknowledge his patience.'],['Mute for the conversation','Give the host room to speak without another voice.']],
    results: [b('A Request with Witnesses','The host asks for the towel and the guest thanks Henderson by name. He considers the earlier landing conversation before deciding whether to lend it. A friendly neighbor also offers the thermos; a wary one points out that your own bathroom contains towels. Either way, the direct thanks takes some stiffness out of his shoulders.',{goodwill:1}),b('A Quiet Negotiation','The host asks for the towel while the guest mutes the call. Henderson appreciates being able to finish a sentence. His willingness to lend still depends on the landing encounter, but nobody adds another noise complaint. The guest applauds silently when the door closes, which the host initially mistakes for poor reception.',{time:-1}),b('A Thank-you through the Door','The host fetches a spare cloth while the guest thanks Henderson aloud. He has no job left to do, so he simply says, "Try a plate under the pot next time." It is advice disguised as a complaint. You finish the cleanup yourselves and leave the next neighbor conversation on warmer terms.',{goodwill:1,time:-1}),b('Domestic Affairs','The host handles the door privately while the guest eats a bite of their own dinner. Henderson returns to 3B with his supplies. Cleanup takes longer with a small bathroom cloth, but the counter becomes safe. "I missed you," says the guest. "Even your forehead camera angle."',{time:-2})]
  },
  {
    title: 'The Chair Has a Name Tag', setting: 'Back at the date table',
    event: 'Both players return to the date call. The guest has placed a folded card on the empty chair opposite them: RESERVED FOR THE PERSON CURRENTLY FIGHTING SAUCE. The host sees it and laughs hard enough to put the fork down again. The moderator sends one last notification asking whether the document may be shared tomorrow. This is a yes-or-no question, not another presentation. The host can answer and silence work notifications, or leave the phone face down to protect dinner. The guest can use the pause to ask an actual date question or improve the ridiculous reservation card.',
    host: 'I had a whole charming anecdote prepared about a train journey. Somehow it has been displaced by a towel. May I still have the chair, or does the sauce have priority seating?',
    guest: 'The chair is yours. The sauce is on a waiting list. Tell me the train story when you can; I would like evidence of your life before this kitchen acquired a supporting cast.',
    goal: 'Close the work interruption and recover a personal conversation.', stakes: 'Leaving the request pending means a later notification; a keepsake can survive the mess.', prompt: 'Finish the final work reply, and choose how to restart the date?',
    h: [['Reply yes and silence work','Send permission to share, then mute work notifications.'],['Put the phone face down','Ignore the request for now and focus on the date.']],
    g: [['Ask for the train story','Invite the host to finish the anecdote they had planned.'],['Make a proper reservation card','Cross out the sauce reference and write the host\'s name.']],
    results: [b('A Story with No Login','The host sends yes, silences work, and tells the train story: they once confidently helped a stranger board a train going in the opposite direction. The guest admits to thanking a ticket machine. For several minutes the only emergency is deciding which of you should ever be trusted with a map.',{work:'Notifications silenced; permission sent',time:2}),b('Reserved by Name','The host finishes the permission reply while the guest rewrites the card using the host\'s name. The crossed-out sauce line remains faintly visible. "Past occupants," the guest explains. The host takes a screenshot. Work is settled and the empty chair suddenly looks less like empty space.',{work:'Notifications silenced; permission sent',keepsake:'A reservation card with your name',time:1}),b('The Train Wins for Now','The host turns the phone over and tells the train story. The guest listens with their chin in one hand until a notification buzzes against the table at the punchline. You laugh anyway. The work request remains unresolved, a small loose end rather than a catastrophe.',{work:'Sharing permission still pending'}),b('A Place Held Open','The host puts the phone down while the guest writes the reservation card. The call now frames two dinner places, one occupied only by a name. A work notification buzzes underneath the host\'s plate. The card is lovely; the notification still needs an answer eventually.',{keepsake:'A reservation card with your name',work:'Sharing permission still pending'})]
  },
  {
    title: 'The Evening Needs a Handle', setting: 'Packing up the kitchen',
    event: 'The dishes are stacked. The host\'s kitchen light flickers once and settles, revealing just how much of the evening has happened under a cupboard. Through the window, the shared roof terrace is open and quiet; a sign says residents may sit there until midnight. The guest has a little balcony or an open window in their own apartment, so you could take the call outside together without pretending to occupy the same place. The host has a portable battery in a drawer and a dessert box, if it survived. Before moving, there is room to pack either carefully or impulsively.',
    host: 'We could have a second location. Films do that when the first location is mostly dishes. The roof has actual chairs and only one known buzzer, several floors below us.',
    guest: 'I can take my half of the date to the window. We could pack like sensible travelers, or declare dessert an emergency and leave before this kitchen books us for another webinar.',
    goal: 'Prepare for a final outdoor stretch of the date.', stakes: 'Packing the battery preserves the video call; rushing leaves less equipment upstairs.', prompt: 'Pack a practical roof kit or chase the remaining quiet time?',
    h: [['Find the portable battery','Pack the charged battery, cable, and two napkins.'],['Carry dessert first','Prioritize the dessert and phone; leave the drawer hunt.']],
    g: [['Check the departure list','Remind the host about the cable and terrace closing time.'],['Choose a song for later','Queue a short song and make the move feel like a date.']],
    results: [b('A Kit for Two Places','The host packs the battery while the guest checks cable and closing time. Two napkins go in the bag, one for a person who is geographically elsewhere. "Optimistic inventory," says the guest. The phone will have enough charge for a proper rooftop call.',{kit:true,time:-1}),b('A Soundtrack with a Cable','The host finds the battery while the guest queues a song. The cable is already attached, so the practical task gets a romantic accompaniment for once. You hum badly enough to make Barnaby answer through the wall. The kit is ready before he can request an encore.',{kit:true}),b('The Checklist Saves a Trip','The host gathers dessert, and the guest catches the missing battery on the departure checklist. Retrieving it costs a short search through a drawer full of mystery adapters. You leave with what you need and one cable neither of you can identify.',{kit:true,time:-2}),b('Dessert on Tour','The host carries the dessert supplies while the guest queues a song. Neither checks the battery drawer. The phone charge will need careful use upstairs, but the move feels wonderfully spontaneous. "If we lose video," says the guest, "I shall assume you have become more handsome in low resolution."',{kit:false,time:2})]
  },
  {
    title: 'Cannoli, Structurally Speaking', setting: 'The final kitchen inspection',
    event: 'Before leaving, the host checks the dessert situation. The box may hold intact cannoli, a picturesque collapse, or nothing at all after Rosa\'s refund. The cupboard contains plain biscuits and jam. At the guest\'s end, a modest square of chocolate waits on a saucer. A fancy dessert would be nice, but the immediate problem is transporting something edible without coating the phone in cream. There is a lidded mug and a small plate. The guest can talk through a layered mug dessert using whatever is available, or invent a grand name for the evidence on the plate.',
    host: 'I had imagined dramatically opening this box. I did not specify which dramatic genre. The biscuits are dependable, though one has a corner missing in a way I find personally relatable.',
    guest: 'Mine is one square of chocolate. If we cut it diagonally, it becomes architecture. Yours can travel in the mug, or we can commit to a plated concept and never explain the concept.',
    goal: 'Make a portable dessert from the food actually left.', stakes: 'A mug travels safely; an exposed plate may lose its topping on the stairs.', prompt: 'Build a travel dessert or embrace the plate presentation?',
    h: [['Layer dessert in the mug','Use cannoli or biscuits and jam in a lidded mug.'],['Arrange dessert on a plate','Present whatever survived as a deliberate little composition.']],
    g: [['Talk through practical layers','Suggest crumb, filling, then a secure lid.'],['Name the dessert extravagantly','Supply a restaurant-style title and a mock tasting note.']],
    results: [b('Dessert with a Seat Belt','The host layers the available ingredients while the guest calls the order. The lid clicks shut. It is not the original restaurant experience, but it can survive stairs. The guest taps their chocolate saucer against the camera: "Mine has no lid. I shall remain stationary."',{dessert:'Travel mug pudding'}),b('The Midnight Reconstruction','The host seals the mug while the guest announces "Midnight Reconstruction, with notes of administrative resilience." The host repeats the title in a terrible restaurant voice. The dessert is secure and the tasting note becomes a message saved in the date chat.',{dessert:'Travel mug pudding',keepsake:'Midnight Reconstruction tasting note'}),b('A Plate with Engineering Notes','The host arranges a plate while the guest recommends a layer of crumbs to stabilize it. The result holds together, but it needs both hands on the stairs. You agree to put the phone in a pocket until reaching the landing. Dessert stays intact at the price of a slower departure.',{dessert:'Carefully plated dessert',time:-2}),b('The Leaning Tower of Whatever','The host makes an ambitious arrangement and the guest gives it a luxurious title. The first step toward the door sends a topping sliding. The host catches it with a napkin and laughs. Dessert is still edible, but it now looks like a map of somewhere you should not drive.',{dessert:'Delicious dessert rubble',time:-1})]
  },
  {
    title: 'Henderson at the Threshold', setting: 'The landing below the roof stairs',
    event: 'Henderson returns as the host locks the apartment. He has Barnaby on a lead and a small tin of shortbread. "Roof?" he asks. "It is quiet up there. I know because I have researched quiet extensively tonight." The roof door is unlocked until midnight, but the folding table belongs to him. Depending on the earlier encounters, the tin is either an offer to share or clearly intended for his own tea. The host can invite him to contribute a brief dessert cameo or promise to keep the terrace peaceful. The guest can greet him through the phone or let the host negotiate without another audience.',
    host: 'We are taking dessert somewhere with fewer appliances. You would be welcome to make a short appearance, but I cannot offer a speaking fee. Most of the budget went into sauce containment.',
    guest: 'Please tell Barnaby his bow tie has been the most stable part of this evening. Also, I can say hello if Henderson wants proof that the phone contains an actual person and not a very involved help desk.',
    goal: 'Arrange the roof visit without imposing on the neighbor.', stakes: 'His earlier willingness affects whether he offers the table and shortbread.', prompt: 'Invite a brief neighbor cameo or preserve a private finale?',
    h: [['Invite a short dessert cameo','Ask whether Henderson wants to bring his tin upstairs briefly.'],['Promise a quiet visit','Explain the plan and give him room to keep his own evening.']],
    g: [['Greet him directly','Say hello and thank him for tolerating the kitchen episode.'],['Wave without interrupting','Let the host do the talking and give Barnaby a small wave.']],
    results: [b('The Supporting Cast Takes a Bow','The host invites Henderson and the guest greets him. He checks the tone against how you treated him earlier. If trust has been built, he brings his folding table and opens the shortbread; otherwise he politely declines the cameo. Barnaby accepts the wave regardless, which is good diplomacy for someone who cannot reach a table.',{goodwill:1}),b('An Invitation with an Exit','The host invites a brief visit while the guest leaves space for Henderson to answer. A friendly Henderson offers the table and tin; a guarded one says he has tea waiting. Neither is trapped into socializing. "Brief is an excellent word," he says, with the expression of someone considering a new notebook title.'),b('A Quiet Promise, Personally Made','The host promises a quiet roof visit and the guest thanks Henderson. He smiles at the screen. There is no demand on his evening, and a neighbor who already trusts you offers the table anyway. Otherwise he simply wishes you a pleasant night. Both are considerably better than a complaint.',{goodwill:1}),b('Permission to Be Alone','The host explains the quiet plan while the guest waves to Barnaby. Henderson nods and returns to his tea, leaving the terrace to you. If earlier goodwill earned an offer of the table, it still stands; otherwise the roof bench will do. The date has room to finish without another audience.')]
  },
  {
    title: 'Three Flights, One Signal Bar', setting: 'Roof stairs and a distant window',
    event: 'On the stairs, the host\'s video turns into a mosaic of forehead and ceiling. The guest can hear footsteps but receives each sentence in two installments. The terrace is one flight above; a sheltered window landing offers a stable signal. If a battery was packed, the phone can use mobile data comfortably. Without it, the charge warning suggests saving video for the view. There is no need to rush or climb while staring at a screen. The host stops on the landing to choose where the date goes next, and the guest sets their own phone safely beside the window.',
    host: 'I am currently either in a stairwell or inside an impressionist painting. I have stopped walking, so you may finish buffering my expression before advising me.',
    guest: 'Your expression has arrived in four separate parcels. The eyebrows seem optimistic. We can keep the call audio-only until you are settled, or make this window our scenic destination and call it intentional.',
    goal: 'Reach a comfortable place with a call you can actually hear.', stakes: 'An unprepared video climb drains the phone and may force a landing finale.', prompt: 'Continue to the roof, or settle at the sheltered landing?',
    h: [['Continue after pocketing the phone','Walk the final flight with the phone safely away.'],['Choose the window landing','Set dessert down on the wide sill and stop here.']],
    g: [['Switch to audio for the move','Save bandwidth until the host is seated.'],['Keep video for the reveal','Wait for the view with the camera running.']],
    results: [b('A Voice Up the Stairs','The host pockets the phone and takes the last flight while the guest switches to audio. Footsteps become the entire soundtrack. Once seated, the host restores video to show the roof lights. Even without a battery, the careful transition leaves enough charge for a short final scene.',{rooftop:true,time:1}),b('The View Costs Pixels','The host pockets the phone while the guest keeps video running. With the packed battery, the roof reveal arrives in a triumphant burst of pixels. Without it, the warning forces a retreat to the landing socket before the call drops. The guest receives a close-up of dessert and declares it a perfectly good skyline.',{time:-2}),b('The Landing Becomes a Venue','The host chooses the sheltered sill while the guest switches to clear audio. You listen to two different streets through two different windows. The host sets the dessert down and restores a steady picture. No roof required: this quiet little square of light belongs to the date now.',{rooftop:false,time:2}),b('A Stable Place to Look','The host sits at the window while the guest keeps video. The image finally sharpens, revealing a view of one chimney and an extremely confident pigeon. "Local celebrity," says the host. The guest salutes it with chocolate. The landing has become a destination instead of a compromise.',{rooftop:false})]
  },
  {
    title: 'The Photograph Nobody Planned', setting: 'Two pools of light',
    event: 'Seated at the roof table, bench, or sheltered landing, the host lifts the dessert into view. Across town or much farther away, the guest holds up their chocolate. The paused song is ready, and there is enough quiet to hear the traffic at both ends. The phone offers a screenshot button. A polished photograph would require moving the mug, hiding the stained napkin, and arranging both faces. An honest one would include the evidence. If work permission was left pending, its notification briefly appears; the host can answer it before taking the picture. Nothing urgent is waiting except the desire to remember this properly.',
    host: 'This is not the photograph I imagined at the start. I imagined better lighting and fewer objects with employment histories. But I think I want this one more.',
    guest: 'I can smile normally, or I can hold my chocolate like an award. Please decide quickly; the award is melting and the committee is hungry. Keep the napkin in shot if you like. It earned its place.',
    goal: 'Choose what to remember about the evening.', stakes: 'The saved keepsake will frame the ending; an unfinished work reply still needs closing.', prompt: 'Stage a lovely picture or keep the evidence of the mishaps?',
    h: [['Keep the napkin in frame','Photograph the real table with its stains and improvised dessert.'],['Arrange a clean portrait','Set the clutter aside and focus the picture on your faces.']],
    g: [['Raise dessert like a trophy','Include the tiny chocolate and celebrate the improvisation.'],['Give the camera a quiet smile','Make the photograph a simple shared portrait.']],
    results: [b('Evidence of an Excellent Mess','The host keeps the stained napkin visible and the guest raises the chocolate trophy. The screenshot catches the host laughing mid-breath. If work permission was pending, the host answers yes before saving it. The photograph looks like a small, extremely specific victory over household logistics.',{keepsake:'Sauce napkin and chocolate trophy photograph',work:'Notifications silenced; permission sent'}),b('The Napkin and the Smile','The host leaves the napkin in frame; the guest gives a quiet smile. The screenshot is unexpectedly tender, the mess sitting beside two people who stayed. The host closes any pending work reply before saving it. "That one," says the guest, before the preview has even finished loading.',{keepsake:'A quiet portrait beside the stained napkin',work:'Notifications silenced; permission sent'}),b('An Award Interrupts the Portrait','The host clears the frame for a neat portrait just as the guest lifts the chocolate trophy. The resulting photograph has one composed face and one delighted confectionery champion. Any pending work reply gets its final yes. The host decides the mismatch is the best part and saves it.',{keepsake:'Formal portrait interrupted by a chocolate trophy',work:'Notifications silenced; permission sent'}),b('A Portrait after Everything','The host sets the mess aside and the guest smiles. You take a simple screenshot with two separate pools of warm light. The host answers any last work request and silences the phone. Nothing in the picture explains the evening. Both of you know that is what the story is for.',{keepsake:'Two windows, one quiet portrait',work:'Notifications silenced; permission sent',time:1})]
  },
  {
    title: 'Midnight, with Receipts', setting: 'The last few minutes of the call',
    event: 'The terrace clock approaches closing time, or the landing grows quiet as the last resident goes downstairs. Henderson gives a small wave from the roof door if he helped; otherwise a light goes out behind the curtain of 3B. The dessert is almost finished. The guest\'s queued song ends before anyone remembers to dance to it. There is no grand test left to pass. There is only the slightly awkward business of ending a call that has finally found its rhythm. The host can suggest a deliberately simple next date or read back the absurd menu of this one. The guest can choose a concrete follow-up or keep the last moment unhurried.',
    host: 'Next time I could make toast. I hesitate to promise that nothing will happen to it, but it has fewer moving parts than a corporate webinar. I would like there to be a next time.',
    guest: 'I would too. We can put something in the calendar that actually belongs there. Or give this evening one last minute without asking it to accomplish anything. I am happy to sit while you finish the last bite.',
    goal: 'Close tonight with a plan or a memory you both chose.', stakes: 'The finale reflects the neighbor, laptop, dessert, and time decisions already made.', prompt: 'How do you say goodnight to this particular date?',
    h: [['Suggest a toast-only sequel','Offer a low-maintenance breakfast date next weekend.'],['Read tonight\'s accidental menu','Recite buzzer, noodles, sauce intervention, and the actual dessert.']],
    g: [['Pick a time for another call','Suggest a specific weekend slot and save it together.'],['Stay for one quiet minute','Set the planning aside briefly and share the last bite.']],
    results: [b('An Appointment That Means It','The host proposes toast next weekend and the guest offers a time. You put it in both calendars, carefully disabling anything labeled webinar. "Dress code?" asks the guest. "Crumbs," says the host. The date ends with a small plan that does not need perfect conditions to be worth keeping.'),b('One More Minute','The host suggests a toast sequel, and the guest asks for one quiet minute before choosing the time. You finish dessert together in separate places. Nobody fills the silence with troubleshooting. When the minute ends, the guest says, "Yes to breakfast," and the host finally stops checking the screen for warnings.'),b('The Menu Gets a Reservation','The host recites the accidental menu while the guest picks a weekend slot. The list gets as far as "sauce intervention" before both start laughing. You save the next call under that name. The future appointment has a terrible title and a very clear purpose.'),b('Goodnight, Bernard','The host reads the menu while the guest stays for the last bite. You add a ceremonial toast to Bernard, Rosa, and a towel with an impressive résumé. The final minute is quiet. The call ends after both have said goodnight twice, neither quite willing to be the first to press the button.')]
  }
];

const chapters = ['The First Spark', 'Mid-Date Meltdown', 'Midnight Frequency'];
export function sceneAt(index: number, f: Fiction): SceneData {
  const s = script[index];
  const chapter = Math.floor(index / 5) + 1;
  const options = (role: string, choices: string[][]): ChoiceOption[] => choices.map(([label,description], i) => ({id:`${role}${i}`,label,description}));
  const callbacks: Record<number,string> = {
    5: f.kit ? 'The tray and towel you prepared are within reach; they can catch a risky spill.' : 'You chose the picture over spill protection. There is no towel under the sauce.',
    6: `${f.laptop.startsWith('Wet') ? 'The wet laptop must stay off; use the phone.' : 'The laptop is dry, but the phone can handle the reply.'} ${f.work === 'Text-only slot agreed' ? 'The moderator already agreed to a text-only contribution.' : 'The live slot has not been cancelled; an introduction may need a firm exit.'}`,
    7: f.neighbor >= 1 ? 'Henderson remembers the courtesy on the landing and is willing to lend his supplies.' : 'Henderson remembers being hurried away. His spare towel is not yet an offer.',
    10: `Rosa left you with: ${f.dessert.toLowerCase()}. Use those ingredients, or the cupboard biscuits, for the final course.`,
    11: f.neighbor >= 2 ? 'Your earlier conversations earned Henderson\'s trust; his folding table and shortbread are available.' : 'Henderson is keeping his evening to himself. The public roof bench remains available.',
    12: f.kit ? 'You packed the charged battery and cable. The roof is within comfortable reach.' : 'You left the battery in the drawer. Audio will preserve charge; continuous video may force a stop.',
    13: `You settled ${f.rooftop ? 'on the roof' : 'at the sheltered window landing'}. Dessert is ${f.dessert.toLowerCase()}.`,
    14: `The laptop is ${f.laptop.toLowerCase()}. You saved ${f.keepsake.toLowerCase()}. These are the facts of this particular evening.`
  };
  return {id:`scene_${chapter}_${index % 5 + 1}`,chapterNumber:chapter,chapterTitle:chapters[chapter-1],sceneNumber:index%5+1,totalScenesInChapter:5,title:s.title,settingName:s.setting,backgroundVariant:chapter===1?'split_date':chapter===2?'webinar_chaos':f.rooftop?'rooftop_glow':'room_alarm',continuity:callbacks[index] || `Dinner buffer: ${f.minutes} minutes. ${f.delivery}.`,immediateGoal:s.goal,stakes:s.stakes,decisionPrompt:s.prompt,dialogue:[{id:'event',speaker:'narrator',text:s.event},{id:'host',speaker:'host',text:s.host,hostPrivateThought:'Choose what you would actually try; your partner has their own part of the problem.'},{id:'guest',speaker:'guest',text:s.guest,guestPrivateThought:'Your help comes from another room. You can support the plan without guessing their choice.'}],choices:{host:options('h',s.h),guest:options('g',s.g)}};
}

export function situation(f: Fiction): TonightSituationState {
  return { timeRemaining:`${f.minutes} minutes of breathing room`,helperStatus:f.neighbor>=2?'Henderson trusts you':f.neighbor>=1?'Henderson is warming up':'Henderson is keeping his distance',deliveryStatus:f.delivery,activeComplication:f.laptop.startsWith('Wet')?'Laptop powered off; continue on phone':f.work,customFacts:[{id:'laptop',label:'Work laptop',value:f.laptop,status:f.laptop.startsWith('Wet')?'warning':'success'},{id:'dessert',label:'Dessert',value:f.dessert},{id:'kit',label:'Prepared supplies',value:f.kit?'Within reach':'Not packed'},{id:'souvenir',label:'Keepsake',value:f.keepsake}] };
}

export function resolve(index: number, hostId: string, guestId: string, f: Fiction): CombinedConsequence {
  const h = Number(hostId[1]), g = Number(guestId[1]);
  const s = script[index], result = s.results[h*2+g];
  const before = {...f};
  const {time=0,goodwill=0,...fields} = result.effect;
  Object.assign(f, fields);
  f.minutes = Math.max(0, f.minutes+time);
  f.neighbor = Math.max(-3, Math.min(6,f.neighbor+goodwill));
  let callback = '';
  if (index===5 && h===1) {
    f.laptop=before.kit?'Dry; towel caught the sauce':'Wet; powered off for repair';
    callback=before.kit?'Your earlier towel setup catches the red line. The laptop stays dry.':'Without the earlier spill kit, glaze reaches the keys. The laptop stays off for the rest of tonight; future calls use the phone.';
  }
  if (index===6 && h===1) {
    if (before.work==='Text-only slot agreed') { f.minutes+=2; callback='The earlier boundary lets the moderator end your slot immediately.'; }
    else { f.minutes=Math.max(0,f.minutes-2); callback='Because you left the live slot scheduled, the moderator tries a follow-up question. Repeating the boundary costs two more minutes.'; }
  }
  if (index===7 && h===0) {
    callback=before.neighbor>=1?'Remembering your earlier courtesy, Henderson lends the towel and pours tea from his thermos.':'Remembering the hurried landing exchange, Henderson keeps the towel. You fetch your own cloth; the cleanup costs two extra minutes.';
    if(before.neighbor>=1) f.kit=true; else f.minutes=Math.max(0,f.minutes-2);
  }
  if(index===11) callback=before.neighbor>=2?'The goodwill you built pays off: Henderson brings his folding table and opens the shortbread tin.':'Henderson keeps his table and shortbread tonight. You can still use the roof bench or the window landing.';
  if(index===12 && h===0 && g===1) { f.rooftop=before.kit; callback=before.kit?'The battery you packed carries the video call all the way to the roof.':'The battery left in the drawer cannot help here. You settle at the landing socket and restore the call.'; }
  const changes=Object.entries(f).filter(([key,value])=>before[key as keyof Fiction]!==value).map(([key,value])=>({field:key,change:String(value),reason:callback || result.title}));
  const labels:Record<string,string>={minutes:'Breathing room (minutes)',neighbor:'Neighbor goodwill',delivery:'Delivery',laptop:'Laptop',dessert:'Dessert',work:'Work interruption',kit:'Supplies ready',rooftop:'Roof reached',keepsake:'Saved memory'};
  const displayChanges=changes.map(c=>({...c,field:labels[c.field],change:c.change==='true'?'Yes':c.change==='false'?'No':c.change}));
  return {title:result.title,description:`${s.h[h][0]} + ${s.g[g][0]}`,hostActionTaken:s.h[h][1],guestActionTaken:s.g[g][1],immediateResult:result.text+(callback?' '+callback:''),tangibleChanges:displayChanges.map(c=>`${c.field}: ${c.change}`),stateChanges:displayChanges,hostReaction:'laughing',guestReaction:'delighted',agreementType:index===0&&h===0&&g===0?'backfired_agreement':index===0&&h===0&&g===1?'accidental_harmony':'comic_mismatch'};
}

export function ending(f: Fiction): StoryEnding {
  const diplomatic=f.neighbor>=3;
  const calm=!f.laptop.startsWith('Wet') && f.minutes>=22;
  const title=diplomatic?'Diplomatic Rescue':calm?'Accidental Soulmates':'Beautiful Chaos';
  const place=f.rooftop?'the roof terrace':'the sheltered window landing';
  const narrative=diplomatic
    ? `Henderson folds away his table after leaving the last shortbread for you. The neighbor who began the night keeping a noise ledger now asks when the two of you will need it again. From ${place}, you introduce the guest properly, without a buzzer as accompaniment. Barnaby receives an entirely ceremonial thank-you; he does not get the chocolate. Courtesy earlier in the evening made this final little gathering possible.`
    : calm ? `At ${place}, you discover that the quiet you protected has finally arrived. The laptop is dry, work is finished, and there is room to finish dessert without checking a countdown. The guest describes the empty chair waiting at their end. The host says that next time the chair deserves an in-person audition. Nothing magical shortened the distance tonight, but you made an ordinary next date feel wonderfully possible.`
    : `At ${place}, you eat the dessert you actually managed to make. ${f.laptop.startsWith('Wet')?'The laptop remains powered off, with a repair to arrange tomorrow; no romantic speech secretly fixes it.':'The laptop survived, although the evening used up more of its breathing room than planned.'} The guest begins a list called THINGS WE CAN NOW HANDLE and immediately crosses out the word handle. You save it as THINGS THAT HAPPENED instead. The mess becomes a story you both helped write, with breakfast still worth planning.`;
  return {id:diplomatic?'diplomatic':calm?'soulmates':'chaos',title,subtitle:'Two places. One very specific evening.',badge:diplomatic?'The Shortbread Accord':calm?'A Date Worth Repeating':'Still Here, Still Laughing',narrative:`${narrative} Rosa delivered the correct dinner after the Bernard mix-up. Your last course was ${f.dessert.toLowerCase()}, and your saved souvenir is ${f.keepsake.toLowerCase()}.`,chaosLevel:diplomatic?'Neighbor-assisted':calm?'Room to breathe':'A story with stains',signatureMoment:f.keepsake,runningJokes:['Bernard, wherever he may dine','Reducing friction, with napkins','The buzzer encore nobody requested']};
}
